"""Create tables Sesions KnowlegeArea Sector

Revision ID: 69bd25284d62
Revises: c68aea737749
Create Date: 2025-05-05 03:33:05.638224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69bd25284d62'
down_revision = 'c68aea737749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_area',
    sa.Column('knowledge_area_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('num_sessions_active', sa.Integer(), nullable=True),
    sa.Column('num_sessions_total', sa.Integer(), nullable=True),
    sa.Column('num_sessions_completed', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('knowledge_area_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sector',
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('num_sessions_active', sa.Integer(), nullable=True),
    sa.Column('num_sessions_total', sa.Integer(), nullable=True),
    sa.Column('knowledge_area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_area_id'], ['knowledge_area.knowledge_area_id'], ),
    sa.PrimaryKeyConstraint('sector_id')
    )
    op.create_table('session_active',
    sa.Column('session_active_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_area_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_area_id'], ['knowledge_area.knowledge_area_id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.sector_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('session_active_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('academic_level', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('register_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('knowledge_area_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sector_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sector', ['sector_id'], ['sector_id'])
        batch_op.create_foreign_key(None, 'knowledge_area', ['knowledge_area_id'], ['knowledge_area_id'])
        batch_op.drop_column('registerType')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registerType', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sector_id')
        batch_op.drop_column('knowledge_area_id')
        batch_op.drop_column('register_type')
        batch_op.drop_column('is_available')
        batch_op.drop_column('academic_level')
        batch_op.drop_column('phone')
        batch_op.drop_column('experience')
        batch_op.drop_column('description')
        batch_op.drop_column('current_role')

    op.drop_table('session_active')
    op.drop_table('sector')
    op.drop_table('knowledge_area')
    # ### end Alembic commands ###
