"""Tabla intermedia users_sector

Revision ID: bd6b06633da4
Revises: 69bd25284d62
Create Date: 2025-05-05 14:00:37.903597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6b06633da4'
down_revision = '69bd25284d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_sector',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.sector_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'sector_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_sector_id_fkey', type_='foreignkey')
        batch_op.drop_column('sector_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_sector_id_fkey', 'sector', ['sector_id'], ['sector_id'])

    op.drop_table('users_sector')
    # ### end Alembic commands ###
